"""Add phone and date_of_birth columns to User

Revision ID: 177eb16e13d9
Revises: 4acb19378dca
Create Date: 2024-11-04 15:57:57.067583

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "177eb16e13d9"
down_revision: Union[str, None] = "4acb19378dca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=mysql.VARCHAR(length=50),
        type_=sqlmodel.sql.sqltypes.AutoString(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
