"""Add phone and date_of_birth columns to User

Revision ID: 4acb19378dca
Revises: 
Create Date: 2024-11-04 15:13:34.212033

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "4acb19378dca"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_0900_ai_ci", length=100
        ),
        type_=sqlmodel.sql.sqltypes.AutoString(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
        type_=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_0900_ai_ci", length=100
        ),
        existing_nullable=False,
    )
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###
